env: local
log_level: debug

server:
  host: "localhost"
  port: 8080

postgres:
  host: "localhost"
  port: 5432
  user: "socialmanage"
  password: "secretpass"
  database: "socialmanagerdb"
  SSLmode: disable

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0

gmail:
  secretPath: "/Users/nikitabelekov/go/src/SocialManager/config/secretGmail.json"
  refreshTime: "30s"

telegram:
  secretPath: "/Users/nikitabelekov/go/src/SocialManager/secretTelegram.json"
  refreshTime: "3m"

secrets:
  jwtSecret: "SECRETKEY"
